# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateField(default=datetime.date(2017, 9, 19)),
        ),
    ]
