# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170919_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(default=datetime.date(2017, 9, 21)),
        ),
    ]
