# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20171006_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.IntegerField(default=1),
        ),
    ]
